# Лабораторная работа 1. Формализация постановок задач исследования КИС
## Вариант 2
###### Выполнил: Борисочкин М. И. РТ5-81Б

In [89]:
# Загрузка датасета
Data <- read.csv("https://raw.githubusercontent.com/junaart/ForStudents/master/KIS/Lab_1/Computers.csv", sep = ",")
View(Data)

X    price speed hd   ram screen cd  multi premium ads trend
1     1   1499  25     80   4  14     no  no    yes     94  1    
2     2   1795  33     85   2  14     no  no    yes     94  1    
3     3   1595  25    170   4  15     no  no    yes     94  1    
4     4   1849  25    170   8  14     no  no    no      94  1    
5     5   3295  33    340  16  14     no  no    yes     94  1    
6     6   3695  66    340  16  14     no  no    yes     94  1    
7     7   1720  25    170   4  14     yes no    yes     94  1    
8     8   1995  50     85   2  14     no  no    yes     94  1    
9     9   2225  50    210   8  14     no  no    yes     94  1    
10   10   2575  50    210   4  15     no  no    yes     94  1    
11   11   2195  33    170   8  15     no  no    yes     94  1    
12   12   2605  66    210   8  14     no  no    yes     94  1    
13   13   2045  50    130   4  14     no  no    yes     94  1    
14   14   2295  25    245   8  14     no  no    yes     94  1    
15   15   2699  50    212   8  14     no  no    yes     94  1    
16   16   2225  50    130   4  14     no  no    yes     94  1    
17   17   1595  33     85   2  14     no  no    yes     94  1    
18   18   2325  33    210   4  15     no  no    yes     94  1    
19   19   2095  33    250   4  15     no  no    yes     94  1    
20   20   4395  66    452   8  14     no  no    yes     94  1    
21   21   1695  33    130   4  14     no  no    yes     94  1    
22   22   2795  66    130   4  14     no  no    yes     94  1    
23   23   2895  25    340  16  14     no  no    yes     94  1    
24   24   2875  50    210   4  17     no  no    yes     94  1    
25   25   4195  50    452   8  14     no  no    yes     94  1    
26   26   1290  33     80   2  14     no  no    yes     94  1    
27   27   1975  33    130   4  14     no  no    yes     94  1    
28   28   3995  33    452   8  14     no  no    yes     94  1    
29   29   3095  33    340  16  14     no  no    yes     94  1    
30   30   3244  66    245   8  14     no  no    yes     94  1    
⋮    ⋮    ⋮     ⋮     ⋮    ⋮   ⋮      ⋮   ⋮     ⋮       ⋮   ⋮    
6230 6230 2344   66    850 16  15     yes no    yes     39  35   
6231 6231 2890  100   1200 24  17     yes no    yes     39  35   
6232 6232 2390   66    850 16  17     yes no    yes     39  35   
6233 6233 1495   66    528  8  14     no  no    yes     39  35   
6234 6234 1844  100    528  8  14     no  no    yes     39  35   
6235 6235 1699   66    630  8  15     no  no    no      39  35   
6236 6236 3290   75   1600 32  17     yes no    yes     39  35   
6237 6237 2790   66   1200 24  17     yes no    yes     39  35   
6238 6238 2845  100   1600 24  15     yes no    yes     39  35   
6239 6239 1744   66    528  8  14     no  no    yes     39  35   
6240 6240 3095  100   1600 32  15     yes no    yes     39  35   
6241 6241 1595  100    528  8  14     no  no    yes     39  35   
6242 6242 2254  100    850 16  15     yes no    yes     39  35   
6243 6243 2723  100   1200 24  15     yes yes   yes     39  35   
6244 6244 2745   66   1600 24  15     yes no    yes     39  35   
6245 6245 3054   75   1600 32  15     yes no    yes     39  35   
6246 6246 2744   66   1200 24  15     yes no    yes     39  35   
6247 6247 1554   66    528  8  14     no  no    yes     39  35   
6248 6248 1654  100    528  8  14     no  no    yes     39  35   
6249 6249 2623   66   1200 24  15     yes yes   yes     39  35   
6250 6250 2095   66    850 16  15     yes no    yes     39  35   
6251 6251 2495   66   1200 24  15     yes no    yes     39  35   
6252 6252 2995   66   1600 32  15     yes no    yes     39  35   
6253 6253 1690   66   1200  8  14     no  no    yes     39  35   
6254 6254 2154   66    850 16  15     yes no    yes     39  35   
6255 6255 1690  100    528  8  15     no  no    yes     39  35   
6256 6256 2223   66    850 16  15     yes yes   yes     39  35   
6257 6257 2654  100   1200 24  15     yes no    yes     39  35   
6258 6258 2195  100    850 16  15     yes no 

### Ограничения:

$6 \leq C_1 \leq 11;
\\ 11 \leq C_2 \leq 21;
\\ 4 \leq C_3 \leq 17;
\\ 8 \leq C_4 \leq 10.$

### Ценновые ограничения:

$C_1 \cdot price_1  + C_2 \cdot price_2  +C_3 \cdot price_3  +C_4 \cdot price_4  \leq 150 000;
\\ C_3 \cdot price_3 \leq 15000.$

### Дополнительные ограничения для сегмента $C_1$:

$ speed \geq 50;
\\ ram \geq 16.$

### Дополнительные ограничения для сегмента $C_2$:

$ speed \geq 30;
\\8 \leq ram \leq 16;
\\ 500 \leq hd \leq 1600.$

### Дополнительные ограничения для сегмента $C_3$:

$ ram \leq 8;
\\hd \leq 1000.$

Компьютер не из премиум сегмента

### Дополнительные ограничения для сегмента $C_4$:

$screen \geq 10.$

Присутвуют CD-ROM и возможность работать с мультимедиа.

### Формирование списков претендетов для каждого сегмента

In [90]:
# Сегмент 1
Data1 <- data.frame()

for (i in c(1:length(rownames(Data))))
{
  if(Data[i, 3] >= 50 & Data[i, 5] >= 16) Data1 <- rbind(Data1, Data[i,])
}

View(Data1)

X    price speed hd   ram screen cd  multi premium ads trend
6      6  3695  66     340 16  14     no  no    yes      94 1    
45    45  3495  50     340 16  14     no  no    yes      94 1    
95    95  2995  66     340 16  14     no  no    yes      95 2    
114  114  2895  50     340 16  14     no  no    yes      95 2    
190  190  2999  66     245 16  15     no  no    yes     100 3    
228  228  2895  50     340 16  14     no  no    yes     100 3    
247  247  3299  66     245 16  15     no  no    yes     100 3    
269  269  2799  50     245 16  15     no  no    yes     100 3    
276  276  2995  66     340 16  14     no  no    yes     100 3    
304  304  2799  50     245 16  15     no  no    yes     108 4    
313  313  2895  50     340 16  14     no  no    yes     108 4    
322  322  2995  66     340 16  14     no  no    yes     108 4    
329  329  3090  66     340 16  14     no  no    yes     108 4    
338  338  2990  50     340 16  14     no  no    yes     108 4    
357  357  3299  66     245 16  15     no  no    yes     108 4    
396  396  2999  66     245 16  15     no  no    yes     108 4    
404  404  2995  66     452 16  14     no  no    yes     139 5    
415  415  3999  66     340 16  17     no  no    yes     139 5    
421  421  3090  66     452 16  14     no  no    yes     139 5    
440  440  2990  50     452 16  14     no  no    yes     139 5    
491  491  3990  66    1000 16  14     no  no    yes     139 5    
497  497  2990  50     452 16  15     no  no    yes     139 5    
513  513  3090  66     452 16  15     no  no    yes     139 5    
526  526  2999  66     245 16  15     no  no    yes     139 5    
533  533  2895  50     452 16  14     no  no    yes     139 5    
553  553  2990  50     452 16  14     no  no    yes     176 6    
561  561  3999  66     345 16  17     no  no    yes     176 6    
578  578  3090  66     452 16  14     no  no    yes     176 6    
611  611  2995  66     452 16  14     no  no    yes     176 6    
616  616  3990  66    1000 16  14     no  no    yes     176 6    
⋮    ⋮    ⋮     ⋮     ⋮    ⋮   ⋮      ⋮   ⋮     ⋮       ⋮   ⋮    
6218 6218 2744   66   1200 24  15     yes no    yes     39  34   
6219 6219 2785   66   1600 24  15     yes no    yes     39  34   
6221 6221 2444  100    850 16  15     yes no    yes     39  35   
6222 6222 2595  100   1200 24  15     yes no    yes     39  35   
6223 6223 2844  100   1200 24  15     yes no    yes     39  35   
6226 6226 3244   75   1600 32  15     yes no    yes     39  35   
6227 6227 3123   75   1600 32  15     yes yes   yes     39  35   
6228 6228 2554   66   1200 24  15     yes no    yes     39  35   
6229 6229 2323  100    850 16  15     yes yes   yes     39  35   
6230 6230 2344   66    850 16  15     yes no    yes     39  35   
6231 6231 2890  100   1200 24  17     yes no    yes     39  35   
6232 6232 2390   66    850 16  17     yes no    yes     39  35   
6236 6236 3290   75   1600 32  17     yes no    yes     39  35   
6237 6237 2790   66   1200 24  17     yes no    yes     39  35   
6238 6238 2845  100   1600 24  15     yes no    yes     39  35   
6240 6240 3095  100   1600 32  15     yes no    yes     39  35   
6242 6242 2254  100    850 16  15     yes no    yes     39  35   
6243 6243 2723  100   1200 24  15     yes yes   yes     39  35   
6244 6244 2745   66   1600 24  15     yes no    yes     39  35   
6245 6245 3054   75   1600 32  15     yes no    yes     39  35   
6246 6246 2744   66   1200 24  15     yes no    yes     39  35   
6249 6249 2623   66   1200 24  15     yes yes   yes     39  35   
6250 6250 2095   66    850 16  15     yes no    yes     39  35   
6251 6251 2495   66   1200 24  15     yes no    yes     39  35   
6252 6252 2995   66   1600 32  15     yes no    yes     39  35   
6254 6254 2154   66    850 16  15     yes no    yes     39  35   
6256 6256 2223   66    850 16  15     yes yes   yes     39  35   
6257 6257 2654  100   1200 24  15     yes no    yes     39  35   
6258 6258 2195  100    850 16  15     yes no 

In [91]:
# Регрессионная модель для первого сегмента
Res1 <- lm(price ~ speed + ram + hd, data = Data1)
Res1


Call:
lm(formula = price ~ speed + ram + hd, data = Data1)

Coefficients:
(Intercept)        speed          ram           hd  
  2250.3280       1.3011      62.7815      -0.8087  


In [92]:
# Сегмент 2
Data2 <- data.frame()

for (i in c(1:length(rownames(Data))))
{
  if(Data[i, 3] >= 30 & Data[i, 5] >= 8 & Data[i, 5] <= 16 & Data[i, 4] >= 500 & Data[i, 4] <= 1600) Data2 <- rbind(Data2, Data[i,])
}

View(Data2)

X    price speed hd   ram screen cd  multi premium ads trend
38    38  3795  66     500  8  14     no  no    yes      94 1    
42    42  3895  66     500  8  15     no  no    yes      94 1    
71    71  4020  66     500  8  14     yes no    yes      94 1    
142  142  4020  66     500  8  14     yes no    yes      95 2    
150  150  3895  66     500  8  15     no  no    yes      95 2    
185  185  3795  66     500  8  14     no  no    yes      95 2    
210  210  3895  66     500  8  15     no  no    yes     100 3    
240  240  3795  66     500  8  14     no  no    yes     100 3    
272  272  4020  66     500  8  14     yes no    yes     100 3    
463  463  3495  66     500  8  14     no  no    yes     139 5    
470  470  3720  66     500  8  14     yes no    yes     139 5    
491  491  3990  66    1000 16  14     no  no    yes     139 5    
510  510  3195  66     540  8  15     no  no    yes     139 5    
583  583  3365  50     540  8  17     no  no    yes     176 6    
585  585  3265  33     540  8  17     no  no    yes     176 6    
597  597  2745  33     540  8  14     no  no    yes     176 6    
616  616  3990  66    1000 16  14     no  no    yes     176 6    
626  626  3595  66     500  8  15     no  no    yes     176 6    
666  666  3789  66     527  8  15     no  no    no      176 6    
673  673  3495  66     500  8  14     no  no    yes     176 6    
684  684  3720  66     500  8  14     yes no    yes     176 6    
687  687  3565  66     540  8  17     no  no    yes     176 6    
688  688  2845  50     540  8  14     no  no    yes     176 6    
690  690  3045  66     540  8  14     no  no    yes     176 6    
719  719  3295  66     545  8  14     no  no    yes     249 7    
721  721  3025  33    1370  8  14     no  no    yes     249 7    
729  729  2425  33     545  8  14     no  no    yes     249 7    
831  831  2999  66     540  8  15     no  no    yes     249 7    
841  841  3789  66     527  8  15     no  no    no      249 7    
843  843  3495  66     500  8  14     no  no    yes     249 7    
⋮    ⋮    ⋮     ⋮     ⋮    ⋮   ⋮      ⋮   ⋮     ⋮       ⋮   ⋮    
6199 6199 1595  100    528  8  14     no  no    yes     39  34   
6204 6204 2195  100    850 16  15     yes no    yes     39  34   
6208 6208 2323  100    850 16  15     yes yes   yes     39  34   
6211 6211 2254  100    850 16  15     yes no    yes     39  34   
6214 6214 1740   66   1200  8  14     no  no    yes     39  34   
6215 6215 1554   66    528  8  14     no  no    yes     39  34   
6216 6216 1654  100    528  8  14     no  no    yes     39  34   
6217 6217 2344   66    850 16  15     yes no    yes     39  34   
6220 6220 1744   66    528  8  14     no  no    yes     39  34   
6221 6221 2444  100    850 16  15     yes no    yes     39  35   
6224 6224 1790  100   1200  8  14     no  no    yes     39  35   
6225 6225 1590   66    528  8  15     no  no    yes     39  35   
6229 6229 2323  100    850 16  15     yes yes   yes     39  35   
6230 6230 2344   66    850 16  15     yes no    yes     39  35   
6232 6232 2390   66    850 16  17     yes no    yes     39  35   
6233 6233 1495   66    528  8  14     no  no    yes     39  35   
6234 6234 1844  100    528  8  14     no  no    yes     39  35   
6235 6235 1699   66    630  8  15     no  no    no      39  35   
6239 6239 1744   66    528  8  14     no  no    yes     39  35   
6241 6241 1595  100    528  8  14     no  no    yes     39  35   
6242 6242 2254  100    850 16  15     yes no    yes     39  35   
6247 6247 1554   66    528  8  14     no  no    yes     39  35   
6248 6248 1654  100    528  8  14     no  no    yes     39  35   
6250 6250 2095   66    850 16  15     yes no    yes     39  35   
6253 6253 1690   66   1200  8  14     no  no    yes     39  35   
6254 6254 2154   66    850 16  15     yes no    yes     39  35   
6255 6255 1690  100    528  8  15     no  no    yes     39  35   
6256 6256 2223   66    850 16  15     yes yes   yes     39  35   
6258 6258 2195  100    850 16  15     yes no 

In [93]:
# Регрессионная модель для второго сегмента
Res2 <- lm(price ~ speed + ram + hd, data = Data2)
Res2


Call:
lm(formula = price ~ speed + ram + hd, data = Data2)

Coefficients:
(Intercept)        speed          ram           hd  
  1660.7498       2.5427      70.8338      -0.3359  


In [94]:
# Сегмент 3
Data3 <- data.frame()

for (i in c(1:length(rownames(Data))))
{
  if( Data[i, 5] <= 8 & Data[i, 4] <= 1000 & Data[i, 9] == "no") Data3 <- rbind(Data3, Data[i,])
}

View(Data3)

X    price speed hd  ram screen cd  multi premium ads trend
4      4  1849  25    170 8   14     no  no    no       94 1    
55    55  2199  33    212 8   14     no  no    no       94 1    
80    80  1629  25     80 8   14     no  no    no       94 1    
86    86  1999  33    120 8   14     no  no    no       94 1    
170  170  1999  33    120 8   14     no  no    no       95 2    
231  231  1999  33    120 8   14     no  no    no      100 3    
367  367  2099  33    120 4   14     no  no    no      108 4    
372  372  3225  66    212 4   15     no  no    no      108 4    
438  438  2019  33    120 4   14     no  no    no      139 5    
487  487  2859  66    212 4   15     no  no    no      139 5    
543  543  2799  33    240 4   14     no  no    no      176 6    
563  563  2999  50    240 4   14     no  no    no      176 6    
575  575  2299  66    120 4   14     no  no    no      176 6    
580  580  2099  33    120 4   14     no  no    no      176 6    
600  600  1675  25    120 4   14     no  no    no      176 6    
605  605  1449  25    120 4   14     no  no    no      176 6    
612  612  3609  66    527 4   15     no  no    no      176 6    
615  615  1799  33    120 4   14     no  no    no      176 6    
625  625  2109  33    120 4   14     no  no    no      176 6    
643  643  1899  25    120 4   14     no  no    no      176 6    
666  666  3789  66    527 8   15     no  no    no      176 6    
698  698  1579  25    120 4   14     no  no    no      176 6    
702  702  2099  33    120 4   14     no  no    no      176 6    
757  757  1599  25    120 4   14     no  no    no      249 7    
760  760  1999  33    120 4   14     no  no    no      249 7    
801  801  2799  33    240 4   14     no  no    no      249 7    
810  810  1579  25    120 4   14     no  no    no      249 7    
841  841  3789  66    527 8   15     no  no    no      249 7    
854  854  2099  33    120 4   14     no  no    no      249 7    
875  875  2299  66    120 4   14     no  no    no      249 7    
⋮    ⋮    ⋮     ⋮     ⋮   ⋮   ⋮      ⋮   ⋮     ⋮       ⋮   ⋮    
5452 5452 1813   50   270 4   14     no  no    no      152 26   
5458 5458 2063   66   270 4   14     no  no    no      152 26   
5519 5519 1699   66   270 4   14     no  no    no      152 26   
5553 5553 1828   66   270 4   14     no  no    no      163 27   
5566 5566 1895   50   364 8   14     no  no    no      163 27   
5578 5578 2145   66   364 8   14     no  no    no      163 27   
5613 5613 2645  100   364 8   14     no  no    no      163 27   
5656 5656 1578   50   270 4   14     no  no    no      163 27   
5668 5668 2328  100   270 4   14     no  no    no      163 27   
5695 5695 1699   66   270 4   14     no  no    no      163 27   
5722 5722 1829   66   420 8   14     no  no    no      132 28   
5835 5835 1666   66   270 4   14     no  no    no      129 29   
5840 5840 2182   66   364 8   14     yes no    no      129 29   
5842 5842 1865   66   270 4   14     yes no    no      129 29   
5845 5845 1574   50   270 4   14     no  no    no      129 29   
5850 5850 1881  100   270 4   14     yes no    no      129 29   
5856 5856 1829   66   420 8   14     no  no    no      129 29   
5887 5887 1773   50   270 4   14     yes no    no      129 29   
5911 5911 2090   50   364 8   14     yes no    no      129 29   
5915 5915 1682  100   270 4   14     no  no    no      129 29   
5918 5918 2378  100   364 8   14     yes no    no      129 29   
5922 5922 2179  100   364 8   14     no  no    no      129 29   
5934 5934 1983   66   364 8   14     no  no    no      129 29   
5963 5963 1891   50   364 8   14     no  no    no      129 29   
5999 5999 1829   66   420 8   14     no  no    no       75 30   
6046 6046 1949   66   420 8   15     no  no    no       52 31   
6101 6101 1949   66   420 8   15     no  no    no       51 32   
6167 6167 1949   66   420 8   15     no  no    no       40 33   
6191 6191 1699   66   630 8   15     no  no    no       39 34   
6235 6235 1699   66   630 8   15     no 

In [95]:
# Регрессионная модель для третьего сегмента
Res3 <- lm(price ~ speed + ram + hd, data = Data3)
Res3


Call:
lm(formula = price ~ speed + ram + hd, data = Data3)

Coefficients:
(Intercept)        speed          ram           hd  
   1225.968        7.888       21.749        2.583  


In [96]:
# Сегмент 4
Data4 <- data.frame()

for (i in c(1:length(rownames(Data))))
{
  if( Data[i, 6] >= 10 & Data[i, 7] == "yes" & Data[i, 8] == "yes") Data4 <- rbind(Data4, Data[i,])
}

View(Data4)

X    price speed hd   ram screen cd  multi premium ads trend
745   745 1945  33    250   4  14     yes yes   yes     249 7    
761   761 1939  50    170   4  14     yes yes   yes     249 7    
781   781 2045  33    250   4  15     yes yes   yes     249 7    
793   793 1829  33    170   4  14     yes yes   yes     249 7    
803   803 2599  50    230   4  14     yes yes   yes     249 7    
836   836 2059  66    170   4  14     yes yes   yes     249 7    
848   848 2225  66    250   4  14     yes yes   yes     249 7    
902   902 2999  66    320   8  15     yes yes   yes     249 7    
912   912 2325  66    250   4  15     yes yes   yes     249 7    
987   987 2225  66    250   4  14     yes yes   yes     298 8    
1019 1019 1795  25    107   4  14     yes yes   yes     298 8    
1037 1037 1799  33    170   4  14     yes yes   yes     298 8    
1054 1054 1945  33    250   4  14     yes yes   yes     298 8    
1064 1064 2045  33    250   4  15     yes yes   yes     298 8    
1074 1074 2195  33    214   8  14     yes yes   yes     298 8    
1083 1083 1895  33    107   4  14     yes yes   yes     298 8    
1084 1084 1919  50    170   4  14     yes yes   yes     298 8    
1101 1101 2325  66    250   4  15     yes yes   yes     298 8    
1107 1107 2999  66    320   8  15     yes yes   yes     298 8    
1116 1116 2095  25    214   8  14     yes yes   yes     298 8    
1124 1124 2039  66    170   4  14     yes yes   yes     298 8    
1197 1197 2599  50    230   4  14     yes yes   yes     298 8    
1265 1265 1890  33    212   4  14     yes yes   yes     246 9    
1285 1285 1999  66    170   4  14     yes yes   yes     246 9    
1333 1333 2190  33    212   8  14     yes yes   yes     246 9    
1387 1387 3194  66    424  16  15     yes yes   yes     246 9    
1399 1399 1879  50    170   4  14     yes yes   yes     246 9    
1405 1405 2390  33    340   8  14     yes yes   yes     246 9    
1454 1454 1769  33    170   4  14     yes yes   yes     246 9    
1459 1459 2690  50    340   8  15     yes yes   yes     246 9    
⋮    ⋮    ⋮     ⋮     ⋮    ⋮   ⋮      ⋮   ⋮     ⋮       ⋮   ⋮    
6087 6087 2299  100    850 16  15     yes yes   yes     52  31   
6090 6090 1599   66    540  8  14     yes yes   yes     52  31   
6092 6092 1723   66    850  8  14     yes yes   yes     51  32   
6093 6093 1699  100    540  8  14     yes yes   yes     51  32   
6097 6097 1649   66    540  8  14     yes yes   yes     51  32   
6098 6098 2049   66    540  8  17     yes yes   yes     51  32   
6102 6102 2623   75   1200 24  15     yes yes   yes     51  32   
6104 6104 2223   66   1000 16  15     yes yes   yes     51  32   
6106 6106 1599   66    545  8  14     yes yes   yes     51  32   
6107 6107 2199   66    850 16  15     yes yes   yes     51  32   
6114 6114 1548   66    540  8  14     yes yes   yes     51  32   
6119 6119 2299  100    850 16  15     yes yes   yes     51  32   
6122 6122 2373  100   1000 16  15     yes yes   yes     51  32   
6128 6128 1599   66    540  8  14     yes yes   yes     51  32   
6136 6136 1873  100    850  8  14     yes yes   yes     51  32   
6146 6146 1823   66    850  8  15     yes yes   yes     40  33   
6149 6149 2223   75   1200 24  15     yes yes   yes     40  33   
6154 6154 1923  100    850  8  15     yes yes   yes     40  33   
6158 6158 1923  100   1000 16  15     yes yes   yes     40  33   
6168 6168 1823   66   1000 16  15     yes yes   yes     40  33   
6186 6186 3123   75   1600 32  15     yes yes   yes     39  34   
6198 6198 2223   66    850 16  15     yes yes   yes     39  34   
6205 6205 2723  100   1200 24  15     yes yes   yes     39  34   
6208 6208 2323  100    850 16  15     yes yes   yes     39  34   
6212 6212 2623   66   1200 24  15     yes yes   yes     39  34   
6227 6227 3123   75   1600 32  15     yes yes   yes     39  35   
6229 6229 2323  100    850 16  15     yes yes   yes     39  35   
6243 6243 2723  100   1200 24  15     yes yes   yes     39  35   
6249 6249 2623   66   1200 24  15     yes yes

In [97]:
# Регрессионная модель для четвёртого сегмента
Res4 <- lm(price ~ speed + ram + hd, data = Data4)
Res4


Call:
lm(formula = price ~ speed + ram + hd, data = Data4)

Coefficients:
(Intercept)        speed          ram           hd  
   1596.783        4.567       91.211       -0.993  


### Построение двухуровневой задачи проектирования КИС

Критерий верхнего уровня:

$H_1 = C_1 \cdot price_1 + C_2 \cdot price_2 + C_3 \cdot price_3 + C_4 \cdot price_4 → min$

Проведём подстановку регриссионных зависимостей:

$H_1 = 2250.328C_1 + 1.3031 \cdot speed_1 \cdot C_1 + 62.7815 \cdot ram_1 \cdot C_1 + (-0.8087 \cdot hd_1 \cdot C_1) +  1660.7498C_2 + 2.5427 \cdot speed_2 \cdot C_2 + 70.8338 \cdot ram_2 \cdot C_2 + (-0.3359 \cdot hd_2 \cdot C_2) +  1225.968C_3 + 7.888 \cdot speed_3 \cdot C_3 + 21.749 \cdot ram_3 \cdot C_3 + 2.583 \cdot hd_3 \cdot C_3 +  1596.783C_4 + 4.567 \cdot speed_4 \cdot C_4 + 91.211 \cdot ram_4 \cdot C_4 + (-0.993 \cdot hd_4 \cdot C_4)$

Введём следующие обозначения:

$x_1 = 2250.328C_1,
\\ x_2 = C_1 \cdot speed_1,
\\ x_3 = C_1 \cdot ram_1,
\\ x_4 = C_1 \cdot hd_1,
\\ x_5 = 1660.7498C_2,
\\ x_6 = C_2 \cdot speed_2,
\\ x_7 = C_2 \cdot ram_2,
\\ x_8 = C_2 \cdot hd_2,
\\ x_9 = 1225.968C_3,
\\ x_{10} = C_3 \cdot speed_3,
\\ x_{11} = C_3 \cdot ram_3,
\\ x_{12} = C_3 \cdot hd_3,
\\ x_{13} = 1596.783C_4,
\\ x_{14} = C_4 \cdot speed_4,
\\ x_{15} = C_4 \cdot ram_4,
\\ x_{16} = C_4 \cdot hd_4.
$

Используя ограничение на количество компьютеров в сегменте и средние значения по их характеристикам, выразим ограничения для $x_i$:

$2250.328 \cdot 6 \leq x_1 \leq 2250.328 \cdot 11;
\\ 70.5263157894737 \cdot 6 \leq x_2 \leq 70.5263157894737 \cdot 11;
\\ 18.1231802911534 \cdot 6 \leq x_3 \leq 18.1231802911534 \cdot 11;
\\ 751.063829787234 \cdot 6 \leq x_4 \leq 751.063829787234 \cdot 11;
\\\
\\1660.7498 \cdot 11 \leq x_5 \leq 1660.7498 \cdot 21;
\\ 63.1110406091371 \cdot 11 \leq x_6 \leq 63.1110406091371 \cdot 21;
\\ 11.6700507614213 \cdot 11 \leq x_7 \leq 11.6700507614213 \cdot 21;
\\ 643.958756345178 \cdot 11 \leq x_8 \leq 643.958756345178 \cdot 21;
\\\
\\ 1225.968 \cdot 4 \leq x_9 \leq 1225.968 \cdot 17;
\\ 44.671568627451 \cdot 4 \leq x_{10} \leq 44.671568627451 \cdot 17;
\\ 4.91503267973856 \cdot 4 \leq x_{11} \leq 4.91503267973856 \cdot 17;
\\ 261.955882352941 \cdot 4 \leq x_{12} \leq 261.955882352941 \cdot 17;
\\\
\\ 1596.783 \cdot 8 \leq x_{13} \leq 1596.783 \cdot 10;
\\ 56.4341351660939 \cdot 8 \leq x_{14} \leq 56.4341351660939 \cdot 10;
\\ 8.92325315005727 \cdot 8 \leq x_{15} \leq 8.92325315005727 \cdot 10;
\\ 476.19587628866 \cdot 8 \leq x_{16} \leq 476.19587628866 \cdot 10.$

Ограничения нижнего уровня:
$ H_1 = x_1 + 1.3031x_2 + 62.7815x_3 + (-0.8087x_4) + x_5 + 2.5427x_6 + 70.8338x_7 + (-0.3359x_8) + x_9 + 7.888x_{10} + 21.749x_{11} + 2.583 x_{12} + x_{13} + 4.567x_{14} + 91.211x_{15} + (-0.993x_{16}) \leq 150000;
\\\
\\C_3 \cdot price_3 = x_9 +  7.888x_{10} + 21.749x_{11} + 2.583x_{12} \leq 15000
$

Определим часиные критерии нижнего уровня:
- Cуммарная производительность (speed, ram) всего серверного оборудования в сегменте $C_1$:

$W_1 = 0.63x_2 + 0.37x_3 → max$

- Cуммарный объем долговременной (винчестер) и оперативной памяти в сегменте $C_2$:

$W_2 = 0.55x_7 + 0.45x_8 → max$

- Производительность процессора (speed) в сегменте $C_3$:

$W_3 = x_{10} → max$

- Объем долговременной памяти (hd) в сегменте $C_4$:

$W_4 = x_{16} → max$

Тогда критерий нижнего уровная равен:

$H_2 = 0.35W_1 + 0.25W_2 + 0.2W_3 + 0.2W_4 = 0.35 \cdot 0.63 \cdot x_2 + 0.35 \cdot 0.37 \cdot x_3 + 0.25 \cdot 0.55 \cdot x_7 + 0.25 \cdot 0.45 \cdot x_8  + 0.2 \cdot x_{10} + 0.2 \cdot x_{16} → max$


Итого:

$
H_1 = x_1 + 1.3031x_2 + 62.7815x_3 + (-0.8087x_4) + x_5 + 2.5427x_6 + 70.8338x_7 + (-0.3359x_8) + x_9 + 7.888x_{10} + 21.749x_{11} + 2.583 x_{12} + x_{13} + 4.567x_{14} + 91.211x_{15} + (-0.993x_{16}) → min;
\\ H_2 = 0.35W_1 + 0.25W_2 + 0.2W_3 + 0.2W_4 = 0.35 \cdot 0.63 \cdot x_2 + 0.35 \cdot 0.37 \cdot x_3 + 0.25 \cdot 0.55 \cdot x_7 + 0.25 \cdot 0.45 \cdot x_8  + 0.2 \cdot x_{10} + 0.2 \cdot x_{16} → max;
\\\
\\2250.328 \cdot 6 \leq x_1 \leq 2250.328 \cdot 11;
\\ 70.5263157894737 \cdot 6 \leq x_2 \leq 70.5263157894737 \cdot 11;
\\ 18.1231802911534 \cdot 6 \leq x_3 \leq 18.1231802911534 \cdot 11;
\\ 751.063829787234 \cdot 6 \leq x_4 \leq 751.063829787234 \cdot 11;
\\\
\\1660.7498 \cdot 11 \leq x_5 \leq 1660.7498 \cdot 21;
\\ 63.1110406091371 \cdot 11 \leq x_6 \leq 63.1110406091371 \cdot 21;
\\ 11.6700507614213 \cdot 11 \leq x_7 \leq 11.6700507614213 \cdot 21;
\\ 643.958756345178 \cdot 11 \leq x_8 \leq 643.958756345178 \cdot 21;
\\\
\\ 1225.968 \cdot 4 \leq x_9 \leq 1225.968 \cdot 17;
\\ 44.671568627451 \cdot 4 \leq x_{10} \leq 44.671568627451 \cdot 17;
\\ 4.91503267973856 \cdot 4 \leq x_{11} \leq 4.91503267973856 \cdot 17;
\\ 261.955882352941 \cdot 4 \leq x_{12} \leq 261.955882352941 \cdot 17;
\\\
\\ 1596.783 \cdot 8 \leq x_{13} \leq 1596.783 \cdot 10;
\\ 56.4341351660939 \cdot 8 \leq x_{14} \leq 56.4341351660939 \cdot 10;
\\ 8.92325315005727 \cdot 8 \leq x_{15} \leq 8.92325315005727 \cdot 10;
\\ 476.19587628866 \cdot 8 \leq x_{16} \leq 476.19587628866 \cdot 10;
\\\
\\x_1 + 1.3031x_2 + 62.7815x_3 + (-0.8087x_4) + x_5 + 2.5427x_6 + 70.8338x_7 + (-0.3359x_8) + x_9 + 7.888x_{10} + 21.749x_{11} + 2.583 x_{12} + x_{13} + 4.567x_{14} + 91.211x_{15} + (-0.993x_{16}) \leq 150000;
\\x_9 +  7.888x_{10} + 21.749x_{11} + 2.583x_{12} \leq 15000.
$

### Решение двухуровневой задачи проектирования КИС

In [98]:
# Установка пакета LpSolve
install.packages("lpSolve")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [99]:
# Подключение библиотеки
library(lpSolve)

In [100]:
# Функции для расчйта H1 и H2
H1 <- function(p){return(sum(c(1, 1.3031, 62.7815, -0.8087, 1, 2.5427, 70.8338, -0.3359, 1, 7.888, 21.749, 2.583, 1, 4.567, 91.211, -0.993)*p))}
H2 <- function(p){return(sum(c(0, 0.35*63, 0.35*0.37, 0, 0, 0, 0.25*0.55, 0.25*0.45, 0, 0.2, 0, 0, 0, 0, 0, 0.2)*p))}

In [101]:
# "Средняя" H2
avgH2 <- H2(c(2250.328, 70.5263157894737, 18.1231802911534, 751.063829787234,
1660.7498, 63.1110406091371, 11.6700507614213, 643.958756345178,
1225.968, 44.671568627451, 4.91503267973856, 261.955882352941,
1596.783, 56.4341351660939, 56.4341351660939, 476.19587628866))
avgH2

[1] 1735.676

In [102]:
# Решение относительно H1 № 1
objective.in <- c(1, 1.3031, 62.7815, -0.8087, 1, 2.5427, 70.8338, -0.3359, 1, 7.888, 21.749, 2.583, 1, 4.567, 91.211, -0.993) # H1
const.mat <- matrix(c(0, 0.35*63, 0.35*0.37, 0, 0, 0, 0.25*0.55, 0.25*0.45, 0, 0.2, 0, 0, 0, 0, 0, 0.2, # H2
1, 1.3031, 62.7815, -0.8087, 1, 2.5427, 70.8338, -0.3359, 1, 7.888, 21.749, 2.583, 1, 4.567, 91.211, -0.993, # full price
0, 0, 0, 0, 0, 0, 0, 0, 1, 7.888, 21.749, 2.583, 0, 0, 0, 0, # C3 price
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x1 >=
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x1 <=
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x2 >=
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x2 <=
0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x3 >=
0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x3 <=
0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x4 >=
0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x4 <=
0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x5 >=
0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x5 <=
0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x6 >=
0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x6 <=
0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x7 >=
0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x7 <=
0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, # x8 >=
0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, # x8 <=
0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, # x9 >=
0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, # x9 <=
0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, # x10 >=
0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, # x10 <=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, # x11 >=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, # x11 <=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, # x12 >=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, # x12 <=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, # x13 >=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, # x13 <=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, # x14 >=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, # x14 <=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, # x15 >=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, # x15 <=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, # x16 >=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ), nrow = 35, byrow = TRUE) # x16 <=

const.dir <- c(">=", "<=", "<=",
">=", "<=", ">=", "<=", ">=", "<=", ">=", "<=",
  ">=", "<=", ">=", "<=", ">=", "<=", ">=", "<=",
  ">=", "<=", ">=", "<=", ">=", "<=", ">=", "<=",
   ">=", "<=", ">=", "<=", ">=", "<=", ">=", "<=")

const.rhs <- c (2581, 150000, 15000, 
2250.328*6, 2250.328*11,
70.5263157894737*6, 70.5263157894737*11,
18.1231802911534*6, 18.1231802911534*11,
751.063829787234*6, 751.063829787234*11,
1660.7498*11, 1660.7498*21,
63.1110406091371*11, 63.1110406091371*21,
11.6700507614213*11, 11.6700507614213*21,
643.958756345178*11, 643.958756345178*21,
1225.968*4, 1225.968*7,
44.671568627451*4, 44.671568627451*7,
4.91503267973856*4, 4.91503267973856*7,
261.955882352941*4, 261.955882352941*7,
1596.783*8, 1596.783*10,
56.4341351660939*8, 56.4341351660939*10,
8.92325315005727*8, 8.92325315005727*10,
476.19587628866*8, 476.19587628866*10)

Res1 <- lp("min", objective.in, const.mat, const.dir, const.rhs)

# Значения целевых функций
H1(Res1$solution)
H2(Res1$solution)

[1] 64849.12

[1] 11871.85

In [103]:
# Решение для H1
Res1$solution

[1] 13501.96800   423.15789   108.73908  8261.70213 18268.24780   694.22145
 [7]   128.37056 13523.13388  4903.87200   178.68627    19.66013  1047.82353
[13] 12774.26400   451.47308    71.38603  4761.95876

In [104]:
# Решение относительно H2 № 1
objective.in <- c(0, 0.35*63, 0.35*0.37, 0, 0, 0, 0.25*0.55, 0.25*0.45, 0, 0.2, 0, 0, 0, 0, 0, 0.2) # H2
const.mat <- matrix(c(1, 1.3031, 62.7815, -0.8087, 1, 2.5427, 70.8338, -0.3359, 1, 7.888, 21.749, 2.583, 1, 4.567, 91.211, -0.993, # H1
1, 1.3031, 62.7815, -0.8087, 1, 2.5427, 70.8338, -0.3359, 1, 6.0573, 120.2834, -0.6677, 1, 4.567, 91.211, -0.993, # full price
0, 0, 0, 0, 0, 0, 0, 0, 1, 7.888, 21.749, 2.583, 0, 0, 0, 0, # C3 price
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x1 >=
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x1 <=
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x2 >=
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x2 <=
0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x3 >=
0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x3 <=
0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x4 >=
0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x4 <=
0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x5 >=
0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x5 <=
0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x6 >=
0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x6 <=
0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x7 >=
0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x7 <=
0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, # x8 >=
0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, # x8 <=
0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, # x9 >=
0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, # x9 <=
0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, # x10 >=
0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, # x10 <=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, # x11 >=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, # x11 <=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, # x12 >=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, # x12 <=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, # x13 >=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, # x13 <=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, # x14 >=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, # x14 <=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, # x15 >=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, # x15 <=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, # x16 >=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ), nrow = 35, byrow = TRUE) # x16 <=

const.dir <- c("<=", "<=", "<=",
">=", "<=", ">=", "<=", ">=", "<=", ">=", "<=",
  ">=", "<=", ">=", "<=", ">=", "<=", ">=", "<=",
  ">=", "<=", ">=", "<=", ">=", "<=", ">=", "<=",
   ">=", "<=", ">=", "<=", ">=", "<=", ">=", "<=")

const.rhs <- c (64850, 150000, 15000, 
2250.328*6, 2250.328*11,
70.5263157894737*6, 70.5263157894737*11,
18.1231802911534*6, 18.1231802911534*11,
751.063829787234*6, 751.063829787234*11,
1660.7498*11, 1660.7498*21,
63.1110406091371*11, 63.1110406091371*21,
11.6700507614213*11, 11.6700507614213*21,
643.958756345178*11, 643.958756345178*21,
1225.968*4, 1225.968*7,
44.671568627451*4, 44.671568627451*7,
4.91503267973856*4, 4.91503267973856*7,
261.955882352941*4, 261.955882352941*7,
1596.783*8, 1596.783*10,
56.4341351660939*8, 56.4341351660939*10,
8.92325315005727*8, 8.92325315005727*10,
476.19587628866*8, 476.19587628866*10)

Res2 <- lp("max", objective.in, const.mat, const.dir, const.rhs)

# Значения целевых функций
H1(Res2$solution)
H2(Res2$solution)

[1] 64850

[1] 11886.73

In [105]:
# Решение для H2
Res2$solution

[1] 13501.96800   423.83274   108.73908  8261.70213 18268.24780   694.22145
 [7]   128.37056 13523.13388  4903.87200   178.68627    19.66013  1047.82353
[13] 12774.26400   451.47308    71.38603  4761.95876

In [106]:
# Решение относительно H1 № 2
objective.in <- c(1, 1.3031, 62.7815, -0.8087, 1, 2.5427, 70.8338, -0.3359, 1, 7.888, 21.749, 2.583, 1, 4.567, 91.211, -0.993) # H1
const.mat <- matrix(c(0, 0.35*63, 0.35*0.37, 0, 0, 0, 0.25*0.55, 0.25*0.45, 0, 0.2, 0, 0, 0, 0, 0, 0.2, # H2
1, 1.3031, 62.7815, -0.8087, 1, 2.5427, 70.8338, -0.3359, 1, 6.0573, 120.2834, -0.6677, 1, 4.567, 91.211, -0.993, # full price
0, 0, 0, 0, 0, 0, 0, 0, 1, 7.888, 21.749, 2.583, 0, 0, 0, 0, # C3 price
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x1 >=
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x1 <=
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x2 >=
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x2 <=
0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x3 >=
0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x3 <=
0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x4 >=
0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x4 <=
0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x5 >=
0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x5 <=
0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x6 >=
0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x6 <=
0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x7 >=
0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x7 <=
0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, # x8 >=
0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, # x8 <=
0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, # x9 >=
0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, # x9 <=
0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, # x10 >=
0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, # x10 <=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, # x11 >=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, # x11 <=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, # x12 >=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, # x12 <=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, # x13 >=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, # x13 <=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, # x14 >=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, # x14 <=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, # x15 >=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, # x15 <=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, # x16 >=
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ), nrow = 35, byrow = TRUE) # x16 <=

const.dir <- c(">=", "<=", "<=",
">=", "<=", ">=", "<=", ">=", "<=", ">=", "<=",
  ">=", "<=", ">=", "<=", ">=", "<=", ">=", "<=",
  ">=", "<=", ">=", "<=", ">=", "<=", ">=", "<=",
   ">=", "<=", ">=", "<=", ">=", "<=", ">=", "<=")

const.rhs <- c (11886, 150000, 15000, 
2250.328*6, 2250.328*11,
70.5263157894737*6, 70.5263157894737*11,
18.1231802911534*6, 18.1231802911534*11,
751.063829787234*6, 751.063829787234*11,
1660.7498*11, 1660.7498*21,
63.1110406091371*11, 63.1110406091371*21,
11.6700507614213*11, 11.6700507614213*21,
643.958756345178*11, 643.958756345178*21,
1225.968*4, 1225.968*7,
44.671568627451*4, 44.671568627451*7,
4.91503267973856*4, 4.91503267973856*7,
261.955882352941*4, 261.955882352941*7,
1596.783*8, 1596.783*10,
56.4341351660939*8, 56.4341351660939*10,
8.92325315005727*8, 8.92325315005727*10,
476.19587628866*8, 476.19587628866*10)

Res <- lp("min", objective.in, const.mat, const.dir, const.rhs)

# Значения целевых функций
H1(Res$solution)
H2(Res$solution)

[1] 64849.96

[1] 11886

In [107]:
# Оптимальное количество компьютеров для каждого сегмента
C <- c(Res1$solution[1]/2250.328, Res1$solution[5]/1660.7498,
 Res1$solution[9]/1225.968, Res1$solution[13]/1596.783)
C

[1]  6 11  4  8

In [108]:
# Оптимальные значения характеристик компьютеров внутри каждого сегмента (идеальные точки)
C1Stats <- c(Res1$solution[2:4]/C[1])
C2Stats <- c(Res1$solution[6:8]/C[2])
C3Stats <- c(Res1$solution[10:12]/C[3])
C4Stats <- c(Res1$solution[14:16]/C[4])

### Парето-оптимизация

Прежде, чем проводить Парето-оптимизацию необходимо отмасштабировать данные в работоспобных вариантах, а также значения идеальных точек.

In [109]:
# Функция нормировки датафрейма
normalizeDF <- function(d){
  maxspeed <- max(d[,3]); minspeed <- min(d[,3])
  maxram <- max(d[,5]); minram <- min(d[,5])
  maxhd <- max(d[,4]); minhd <- min(d[,4])

  newspeed <- (d$speed - minspeed)*100/(maxspeed - minspeed)
  newram <- (d$ram - minram)*100/(maxram - minram)
  newhd <- (d$hd - minhd)*100/(maxhd - minhd)

  normDF <- data.frame(newspeed, newram, newhd)
  rownames(normDF) <- rownames(d)
  colnames(normDF) <- c("speed", "ram", "hd")
  return(normDF)
}

In [110]:
# Функция нормировки идеальной точки
normalizePoint <- function(p, d){
   maxspeed <- max(d[,3]); minspeed <- min(d[,3])
  maxram <- max(d[,5]); minram <- min(d[,5])
  maxhd <- max(d[,4]); minhd <- min(d[,4])

  newspeed <- (p[1] - minspeed)*100/(maxspeed - minspeed)
  newram <- (p[2] - minram)*100/(maxram - minram)
  newhd <- (p[3] - minhd)*100/(maxhd - minhd)

  normPoint <- c(newspeed, newram, newhd)
  return(normPoint)
}

In [111]:
DPareto <- function(X, Y){
  p <- TRUE; l <- FALSE; i <- 1;
  while(p & (i <= length(X))){
    if(X[i] < Y[i]) p <- FALSE
    if(X[i] > Y[i]) l <- TRUE
    i <- i+1
  }
  if(!p | !l) return (FALSE)
  else return (TRUE)
}

In [112]:
# Функция евклидого расстояния
distance <- function(A, B){ return(sqrt(sum((A-B)^2))) }

#### Сегмент 1

In [113]:
# Масштабирование датасета
normData1 <- normalizeDF(Data1)
normData1

speed ram hd       
6    32    0    5.121294
45    0    0    5.121294
95   32    0    5.121294
114   0    0    5.121294
190  32    0    0.000000
228   0    0    5.121294
247  32    0    0.000000
269   0    0    0.000000
276  32    0    5.121294
304   0    0    0.000000
313   0    0    5.121294
322  32    0    5.121294
329  32    0    5.121294
338   0    0    5.121294
357  32    0    0.000000
396  32    0    0.000000
404  32    0   11.159030
415  32    0    5.121294
421  32    0   11.159030
440   0    0   11.159030
491  32    0   40.700809
497   0    0   11.159030
513  32    0   11.159030
526  32    0    0.000000
533   0    0   11.159030
553   0    0   11.159030
561  32    0    5.390836
578  32    0   11.159030
611  32    0   11.159030
616  32    0   40.700809
⋮    ⋮     ⋮   ⋮        
6218  32    50 51.48248 
6219  32    50 73.04582 
6221 100     0 32.61456 
6222 100    50 51.48248 
6223 100    50 51.48248 
6226  50   100 73.04582 
6227  50   100 73.04582 
6228  32    50 51.48248 
6229 100     0 32.61456 
6230  32     0 32.61456 
6231 100    50 51.48248 
6232  32     0 32.61456 
6236  50   100 73.04582 
6237  32    50 51.48248 
6238 100    50 73.04582 
6240 100   100 73.04582 
6242 100     0 32.61456 
6243 100    50 51.48248 
6244  32    50 73.04582 
6245  50   100 73.04582 
6246  32    50 51.48248 
6249  32    50 51.48248 
6250  32     0 32.61456 
6251  32    50 51.48248 
6252  32   100 73.04582 
6254  32     0 32.61456 
6256  32     0 32.61456 
6257 100    50 51.48248 
6258 100     0 32.61456 
6259 100     0 32.61456

In [114]:
# Поиск Парето-оптимальных решений
result1 <- c()

for(i in c(1:length(rownames(normData1)))){
  p <- TRUE
  for (j in c(1:length(rownames(normData1)))){
    if(DPareto(normData1[j,], normData1[i,])) p <- FALSE
  }
  if(p) result1 <- c(result1, rownames(normData1)[i])
}

result1

[1] "5961" "6200" "6240"

In [115]:
# Расстояние до иделаьной точки
for(i in result1) print(paste(i, ":", as.character(distance(normalizePoint(C1Stats, Data1), normData1[i,]))))

[1] "5961 : 71.9040952143694"
[1] "6200 : 105.553251250941"
[1] "6240 : 105.553251250941"


In [116]:
# Лучший возможный вариант для сегмента C1
Data1["5961", ]

X    price speed hd   ram screen cd  multi premium ads trend
5961 5961 3175  100   2100 16  15     yes yes   yes     129 29

#### Сегмент 2

In [117]:
# Масштабирование датасета
normData2 <- normalizeDF(Data2)
normData2

speed     ram hd        
38   49.25373    0   0.000000
42   49.25373    0   0.000000
71   49.25373    0   0.000000
142  49.25373    0   0.000000
150  49.25373    0   0.000000
185  49.25373    0   0.000000
210  49.25373    0   0.000000
240  49.25373    0   0.000000
272  49.25373    0   0.000000
463  49.25373    0   0.000000
470  49.25373    0   0.000000
491  49.25373  100  57.471264
510  49.25373    0   4.597701
583  25.37313    0   4.597701
585   0.00000    0   4.597701
597   0.00000    0   4.597701
616  49.25373  100  57.471264
626  49.25373    0   0.000000
666  49.25373    0   3.103448
673  49.25373    0   0.000000
684  49.25373    0   0.000000
687  49.25373    0   4.597701
688  25.37313    0   4.597701
690  49.25373    0   4.597701
719  49.25373    0   5.172414
721   0.00000    0 100.000000
729   0.00000    0   5.172414
831  49.25373    0   4.597701
841  49.25373    0   3.103448
843  49.25373    0   0.000000
⋮    ⋮         ⋮   ⋮         
6199 100.00000   0  3.218391 
6204 100.00000 100 40.229885 
6208 100.00000 100 40.229885 
6211 100.00000 100 40.229885 
6214  49.25373   0 80.459770 
6215  49.25373   0  3.218391 
6216 100.00000   0  3.218391 
6217  49.25373 100 40.229885 
6220  49.25373   0  3.218391 
6221 100.00000 100 40.229885 
6224 100.00000   0 80.459770 
6225  49.25373   0  3.218391 
6229 100.00000 100 40.229885 
6230  49.25373 100 40.229885 
6232  49.25373 100 40.229885 
6233  49.25373   0  3.218391 
6234 100.00000   0  3.218391 
6235  49.25373   0 14.942529 
6239  49.25373   0  3.218391 
6241 100.00000   0  3.218391 
6242 100.00000 100 40.229885 
6247  49.25373   0  3.218391 
6248 100.00000   0  3.218391 
6250  49.25373 100 40.229885 
6253  49.25373   0 80.459770 
6254  49.25373 100 40.229885 
6255 100.00000   0  3.218391 
6256  49.25373 100 40.229885 
6258 100.00000 100 40.229885 
6259 100.00000 100 40.229885

In [118]:
# Поиск Парето-оптимальных решений
result2 <- c()

for(i in c(1:length(rownames(normData2)))){
  p <- TRUE
  for (j in c(1:length(rownames(normData2)))){
    if(DPareto(normData2[j,], normData2[i,])) p <- FALSE
  }
  if(p) result2 <- c(result2, rownames(normData2)[i])
}

result2

[1] "901"  "1102" "1525" "1836" "5882"

In [119]:
# Расстояние до иделаьной точки
for(i in result2) print(paste(i, ":", as.character(distance(normalizePoint(C2Stats, Data2), normData2[i,]))))

[1] "901 : 48.8306395163606"
[1] "1102 : 48.8306395163606"
[1] "1525 : 48.8306395163606"
[1] "1836 : 48.8306395163606"
[1] "5882 : 77.2867206815167"


In [150]:
# Лучший возможный вариант для сегмента C2
Data2["1836", ]

X    price speed hd   ram screen cd multi premium ads trend
1836 1836 3205  66    1370 8   14     no no    yes     259 11

#### Сегмент 3

In [121]:
# Масштабирование датасета
normData3 <- normalizeDF(Data3)
normData3

speed     ram hd      
4     0.00000  100 13.88889
55   10.66667  100 20.37037
80    0.00000  100  0.00000
86   10.66667  100  6.17284
170  10.66667  100  6.17284
231  10.66667  100  6.17284
367  10.66667    0  6.17284
372  54.66667    0 20.37037
438  10.66667    0  6.17284
487  54.66667    0 20.37037
543  10.66667    0 24.69136
563  33.33333    0 24.69136
575  54.66667    0  6.17284
580  10.66667    0  6.17284
600   0.00000    0  6.17284
605   0.00000    0  6.17284
612  54.66667    0 68.98148
615  10.66667    0  6.17284
625  10.66667    0  6.17284
643   0.00000    0  6.17284
666  54.66667  100 68.98148
698   0.00000    0  6.17284
702  10.66667    0  6.17284
757   0.00000    0  6.17284
760  10.66667    0  6.17284
801  10.66667    0 24.69136
810   0.00000    0  6.17284
841  54.66667  100 68.98148
854  10.66667    0  6.17284
875  54.66667    0  6.17284
⋮    ⋮         ⋮   ⋮       
5452  33.33333   0 29.32099
5458  54.66667   0 29.32099
5519  54.66667   0 29.32099
5553  54.66667   0 29.32099
5566  33.33333 100 43.82716
5578  54.66667 100 43.82716
5613 100.00000 100 43.82716
5656  33.33333   0 29.32099
5668 100.00000   0 29.32099
5695  54.66667   0 29.32099
5722  54.66667 100 52.46914
5835  54.66667   0 29.32099
5840  54.66667 100 43.82716
5842  54.66667   0 29.32099
5845  33.33333   0 29.32099
5850 100.00000   0 29.32099
5856  54.66667 100 52.46914
5887  33.33333   0 29.32099
5911  33.33333 100 43.82716
5915 100.00000   0 29.32099
5918 100.00000 100 43.82716
5922 100.00000 100 43.82716
5934  54.66667 100 43.82716
5963  33.33333 100 43.82716
5999  54.66667 100 52.46914
6046  54.66667 100 52.46914
6101  54.66667 100 52.46914
6167  54.66667 100 52.46914
6191  54.66667 100 84.87654
6235  54.66667 100 84.87654

In [122]:
# Поиск Парето-оптимальных решений
result3 <- c()

for(i in c(1:length(rownames(normData3)))){
  p <- TRUE
  for (j in c(1:length(rownames(normData3)))){
    if(DPareto(normData3[j,], normData3[i,])) p <- FALSE
  }
  if(p) result3 <- c(result3, rownames(normData3)[i])
}

result3

[1] "4025" "4089" "4126" "4355" "4366" "4428" "4637" "4646" "4686" "4695"
[11] "4701" "4756" "4900"

In [123]:
# Расстояние до иделаьной точки
for(i in result3) print(paste(i, ":", as.character(distance(normalizePoint(C3Stats, Data3), normData3[i,]))))

[1] "4025 : 128.696845381986"
[1] "4089 : 128.696845381986"
[1] "4126 : 128.696845381986"
[1] "4355 : 128.696845381986"
[1] "4366 : 128.696845381986"
[1] "4428 : 128.696845381986"
[1] "4637 : 128.696845381986"
[1] "4646 : 128.696845381986"
[1] "4686 : 128.696845381986"
[1] "4695 : 128.696845381986"
[1] "4701 : 128.696845381986"
[1] "4756 : 128.696845381986"
[1] "4900 : 128.696845381986"


In [146]:
# Лучший возможный вариант для сегмента C3
Data3["4900", ]

X    price speed hd  ram screen cd multi premium ads trend
4900 4900 3149  100   728 8   14     no no    no      191 23

#### Сегмент 4

In [125]:
# Масштабирование датасета
normData4 <- normalizeDF(Data4)
normData4

speed     ram       hd       
745  10.66667   6.666667  7.175113
761  33.33333   6.666667  3.161064
781  10.66667   6.666667  7.175113
793  10.66667   6.666667  3.161064
803  33.33333   6.666667  6.171601
836  54.66667   6.666667  3.161064
848  54.66667   6.666667  7.175113
902  54.66667  20.000000 10.687406
912  54.66667   6.666667  7.175113
987  54.66667   6.666667  7.175113
1019  0.00000   6.666667  0.000000
1037 10.66667   6.666667  3.161064
1054 10.66667   6.666667  7.175113
1064 10.66667   6.666667  7.175113
1074 10.66667  20.000000  5.368791
1083 10.66667   6.666667  0.000000
1084 33.33333   6.666667  3.161064
1101 54.66667   6.666667  7.175113
1107 54.66667  20.000000 10.687406
1116  0.00000  20.000000  5.368791
1124 54.66667   6.666667  3.161064
1197 33.33333   6.666667  6.171601
1265 10.66667   6.666667  5.268440
1285 54.66667   6.666667  3.161064
1333 10.66667  20.000000  5.268440
1387 54.66667  46.666667 15.905670
1399 33.33333   6.666667  3.161064
1405 10.66667  20.000000 11.690918
1454 10.66667   6.666667  3.161064
1459 33.33333  20.000000 11.690918
⋮    ⋮         ⋮         ⋮        
6087 100.00000  46.66667 37.28048 
6090  54.66667  20.00000 21.72604 
6092  54.66667  20.00000 37.28048 
6093 100.00000  20.00000 21.72604 
6097  54.66667  20.00000 21.72604 
6098  54.66667  20.00000 21.72604 
6102  66.66667  73.33333 54.84195 
6104  54.66667  46.66667 44.80682 
6106  54.66667  20.00000 21.97692 
6107  54.66667  46.66667 37.28048 
6114  54.66667  20.00000 21.72604 
6119 100.00000  46.66667 37.28048 
6122 100.00000  46.66667 44.80682 
6128  54.66667  20.00000 21.72604 
6136 100.00000  20.00000 37.28048 
6146  54.66667  20.00000 37.28048 
6149  66.66667  73.33333 54.84195 
6154 100.00000  20.00000 37.28048 
6158 100.00000  46.66667 44.80682 
6168  54.66667  46.66667 44.80682 
6186  66.66667 100.00000 74.91219 
6198  54.66667  46.66667 37.28048 
6205 100.00000  73.33333 54.84195 
6208 100.00000  46.66667 37.28048 
6212  54.66667  73.33333 54.84195 
6227  66.66667 100.00000 74.91219 
6229 100.00000  46.66667 37.28048 
6243 100.00000  73.33333 54.84195 
6249  54.66667  73.33333 54.84195 
6256  54.66667  46.66667 37.28048

In [126]:
# Поиск Парето-оптимальных решений
result4 <- c()

for(i in c(1:length(rownames(normData4)))){
  p <- TRUE
  for (j in c(1:length(rownames(normData4)))){
    if(DPareto(normData4[j,], normData4[i,])) p <- FALSE
  }
  if(p) result4 <- c(result4, rownames(normData4)[i])
}

result4

[1] "5961" "6186" "6205" "6227" "6243"

In [127]:
# Расстояние до иделаьной точки
for(i in result4) print(paste(i, ":", as.character(distance(normalizePoint(C4Stats, Data4), normData4[i,]))))

[1] "5961 : 98.1386637960238"
[1] "6186 : 95.2441405212874"
[1] "6205 : 82.5869150694837"
[1] "6227 : 95.2441405212874"
[1] "6243 : 82.5869150694837"


In [131]:
# Лучший возможный вариант для сегмента C4
Data1["6205", ]

X    price speed hd   ram screen cd  multi premium ads trend
6205 6205 2723  100   1200 24  15     yes yes   yes     39  34

### Ответ
- Сегмент C1: 6 компьютеров под номером 5961;
- Сегмент C2: 11 компьютеров под номером 1836;
- Сегмент C3: 4 компьютера под номером 4900;
- Сегмент C4: 8 компьютеров под номером 6205.